# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # official ubuntu boxes
  # direct links
  config.vm.box     = "ubuntu/trusty64"
  config.vm.box_url = "https://atlas.hashicorp.com/ubuntu/boxes/trusty64"
  
  # system memory
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
  end

  # default ip address
  config.vm.network "private_network", ip: "192.168.33.10"

  # setup puppet
  config.vm.provision :shell, :path => "scripts/upgrade-puppet.sh"

  config.vm.synced_folder 'puppet/logs', "/tmp/vagrant-puppet/logs"

  # puppet configuration
  config.vm.provision "puppet" do |puppet|
    puppet.module_path    = ["puppet/modules/", "../.."]
    puppet.manifests_path = "../tests"
    puppet.manifest_file  = "test.pp"
    #puppet.options        = "--logdest /tmp/vagrant-puppet/logs/puppet.log"
  end
end
